### ISSUE TITLE
Japanese Translation for Bitshares

### ISSUE THREAD

**Issue by VANCO-JP** [BitSharesEurope/docs.bitshares.eu#14]
My team at Vantage Corp (aka:VANCO) will proceed estimation on Bitshares.org main site translation for Japanese.

Basically there are 6 Main pages  to be translated to Japanese:

(1)  Main Dashboard page:  https://bitshares.org/wallet/#/dashboard
(2)  Account overview: https://bitshares.org/wallet/#/account/vantage-co/overview
(3)  Transfer wallet:  https://bitshares.org/wallet/#/transfer
(4)  Exchange Market:   https://bitshares.org/wallet/#/market/USD_BTS
(5)  Deposit and withdraw:  https://bitshares.org/wallet/#/deposit-withdraw/
(6)  Setting Area:
      -Setting
      -Explore
      -Help (There are 18 tables of  contents) 

We  need to start initate counting and estimate total words of all 6 areas with direct professional translation.  It is estimated to have 30 days for full translations of words.

Will estimate each professional translation and each word will cost between JPY50-100 yen.

Deliverables:
(1)  Full professional translation of all 6 main pages and area
(2)  Estimated to have full translation in 30 days.
(3)  Estimate the budget within 7 days byt the end of August 30th, 2017

**Comment by xeroc** [comment]
Please note that this repository is specifically for `docs.bitshares.org` and not for the main web page.
The main page is on github.com/bitshares/bitshares.github.io
