### ISSUE TITLE
contributing with linux

### ISSUE THREAD

**Issue by oxarbitrage** [BitSharesEurope/docs.bitshares.eu#27]
We need to add the steps to install the requirements for linux. ubuntu/debian is the most used and maybe windows will be nice as well. currently only OSX commands are available at http://docs.bitshares.org/meta/contribute-docs.html and https://github.com/bitshares/docs.bitshares.org

**Comment by pnomolos** [comment]
I use Ubuntu daily so maybe I can take a stab at adding the relevant commands.
