### ISSUE TITLE
Unclear reference to "cli_full_wallet"

### ISSUE THREAD

**Issue by neura-sx** [BitSharesEurope/docs.bitshares.eu#4]
http://docs.bitshares.eu/api/rpc.html

> Wallet specific commands, such as transfer and market orders, are only available if connecting to `cli_wallet` or `cli_full_wallet` and will only execute of the wallet is unlocked.

What do you mean by `cli_full_wallet`?

**Comment by xeroc** [comment]
`cli_full_wallet` has been a separated binary that got removed from the sources by now. Thanks for the hint. I will remove it from the docs
