### ISSUE TITLE
Suggested improvement to the "enable-stale-production" explanation

### ISSUE THREAD

**Issue by neura-sx** [BitSharesEurope/docs.bitshares.eu#5]
I propose to replace the fragment referring to the `enable-stale-production` flag on this page
http://docs.bitshares.eu/testnet/3-init-blockchain.html
with the following more precise explanation:

> When is it safe to stop using the `enable-stale-production` flag?

The `enable-stale-production` flag tells the witness node to produce on a chain with zero blocks or very old blocks. It can be specified as a parameter on the command line or directly in the `config.ini` file.

If you are running your testnet on a single machine, you should keep this flag on at all times. This way you ensure that blocks are generated even if the blockchain has been stuck due to a server crash or something similar.

If you share your testnet with other users and the witness participation is high enough, you can safely switch this flag off. In this case, when starting up, your witness node will connect to another existing witness node over the p2p network, or get the blockchain state from an existing data directory.

**Comment by neura-sx** [comment]
@xeroc , shall I make suggestions like this one as an issue or create proper pull requests? 

Please note that if I use pull requests then my code might have some styling issues as I'll have to do without having a proper HTML preview. 

I'm on Windows so setting up the whole thing as you described it here:
http://docs.bitshares.eu/meta/contribute-docs.html
is a bit out my reach at this moment.

**Comment by xeroc** [comment]
@neura-sx 
Thanks for your contrinutions. You are free to send pull requests, but let me tell you that I am currently redoing this page already. I missed one crucial point that prevents people now from connecting their witness nodes with the testnet. Need to do some more testing and figuring things out, first.

In the mean time. Please go ahead and send a PR. I can clean up "the style" :)
