### ISSUE TITLE
Voting screenshots are out-of-date

### ISSUE THREAD

**Issue by pnomolos** [BitSharesEurope/docs.bitshares.eu#50]
They don't appear to have been updated in about 2 years, so the pictures are of the old UI.

**Comment by abitmore** [comment]
It's hard to keep the screenshots up to date since the UI is under heavy development and changes frequently. We need a better way.

**Comment by pnomolos** [comment]
Hmm, I'll see what I can come up with.

**Comment by abitmore** [comment]
@pnomolos if you have interest in contributing to the docs, please contact @xeroc, I think the work should be included in this proposal: https://bitsharestalk.org/index.php?topic=25916.0 or another one.

**Comment by pnomolos** [comment]
@abitmore OK thanks!  Should I leave the issue open or close it since this is hopefully seeing an overhaul?
