### ISSUE TITLE
how to get an address 

### ISSUE THREAD

**Issue by zychappy** [BitSharesEurope/docs.bitshares.eu#58]
the rule about 
address = ‘BTS’+base58(ripemd(sha512(compressed_pub))) (checksum obviated) 
doesnt work!
I got key arrays with suggest_brain_key,and I tried to generate keys by golang,and I got correct priv_key  but not base58Code.
```
suggest_brain_key
{
  "brain_priv_key": "STRIP BEHEARS PASTERN HIND CUORIN SPATE BEEISH BETTONG COMELY LOP FREEWAY RUNG TRAMMEL CARABID CLIPEUS TARATAH",
  "wif_priv_key": "5JUxQdUCRv9sT1uvZHZb524z3p5zYR8PgzYSf47VY2fJMYjdUhV",
  "pub_key": "BTS57nastVRTyqBa69Q5vsUjWouiUNYZuoEybaoE5hwymhk7LrVC6"
}
```
***
```
func genPrivkey(brainKey string) *btcec.PrivateKey {

	s := brainKey + " 0"
	h := sha512.New()
	h.Write([]byte(s))
	bs := h.Sum(nil)

	h2 := sha256.New()
	h2.Write(bs)
	bss := h2.Sum(nil)

	seed := bss[:32]
	s256 := btcec.S256()
	priv, _ := btcec.PrivKeyFromBytes(s256, seed)

	privKeyWif, _ := btcutil.NewWIF(priv, &chaincfg.MainNetParams, false)

	fmt.Println(privKeyWif.String())//5JUxQdUCRv9sT1uvZHZb524z3p5zYR8PgzYSf47VY2fJMYjdUhV

	return priv
}
```
***
```
func genPubkey(privKey *btcec.PrivateKey) string {
	//address = ‘BTS’+base58(ripemd(sha512(compressed_pub))) (checksum obviated) 也不对
	cpk := privKey.PubKey().SerializeCompressed()
	fmt.Println(cpk)
	fmt.Printf("%x\n", cpk)
	sha := sha512.New()
	sha.Write(cpk)
	sha512 := sha.Sum(nil)
	fmt.Println(sha512)
	ripemd := ripemd160.New()
	ripemd.Write(sha512)
	addr := ripemd.Sum(nil)
	fmt.Println(addr)
	b58Code := base58.Encode(addr)
	fmt.Println("base58", b58Code)//4Kx1wmW9xKLkQ21xKDBm7VfHuEvv
	return b58Code
}
```

**Comment by clockworkgr** [comment]
`address = ‘BTS’+base58(ripemd(sha512(compressed_pub))) (checksum obviated)`

This rule I believe is for old BTS addresses in the genesis block.

The public keys used in active/owner/memo authorities in BitShares are much simpler and are only a checksummed version of the public key.

You should be doing:

`BTS+Base58(<compressed_public_key>+<first_4_bytes_of_RIPEMD160(compressed_public_key)>)`

**Comment by zychappy** [comment]
> `address = ‘BTS’+base58(ripemd(sha512(compressed_pub))) (checksum obviated)`
> 
> This rule I believe is for old BTS addresses in the genesis block.
> 
> The public keys used in active/owner/memo authorities in BitShares are much simpler and are only a checksummed version of the public key.
> 
> You should be doing:
> 
> `BTS+Base58(<compressed_public_key>+<first_4_bytes_of_RIPEMD160(compressed_public_key)>)`

It works! thank you very much!
