### ISSUE TITLE
Description of a private testnet is missing

### ISSUE THREAD

**Issue by neura-sx** [BitSharesEurope/docs.bitshares.eu#6]
@xeroc 
After the recent updates, you've replaced the previous content regarding **private** testnet with a description which is devoted entirely to the existing **public** testnet.

I agree that a private network is just a special case of a more general public one, nevertheless I think most developers would want to start with a private one first, as in most cases this is what they need and it is much easier to set up.

So please consider using this description as a complementary guide for those who need only a private network:
https://neura-sx.gitbooks.io/graphene-book/content/book/testnets/tutorial-private-testnet.html

**Comment by neura-sx** [comment]
Here is the source code for the markdown:
https://github.com/neura-sx/graphene-book/blob/master/book/testnets/tutorial-private-testnet.md

**Comment by xeroc** [comment]
Very cool .. Do you mind if I just copy pase your content? I plan to push a new update to the docs today that makes clear that the content is licensed under CC/LGPL or MIT (not sure which one yet, probably CC). What that be ok for you?

**Comment by neura-sx** [comment]
Surely, I'm very OK with that.

**Comment by neura-sx** [comment]
Maybe you'll need to replace this sentence:

> Open a **Command Prompt** window and switch the current directory...

as the _Command Prompt_ name is specific to Windows. I don't know what's the universal name for this kind of console regardless of OS.

**Comment by xeroc** [comment]
command prompt is fine in most operating systems afaik
https://github.com/BitSharesEurope/docs.bitshares.eu/commit/75ab4e951300fd8d3e0460be6aba0dd2763e171b
